language: cpp

before_script:
  - chmod +x cbp2make

script:
  - ./cbp2make -in BaseProject.cbp -out Makefile
  - make
  - bin/Test/BaseProject

after_success:
  - bash <(curl -s https://codecov.io/bash)
